test("all 0", function() {
  var game = new KataBowlingGame();
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  game.roll(0);
  ok(0 == game.score(), "all 0 should equal to 0! Current Value is: " + game.score());
});
